[package]
name = "mdbook-git-info"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
chrono = "0.4.19"
clap = "2.33"
mdbook = "0.4"
pulldown-cmark = "0.7"
pulldown-cmark-to-cmark = "4.0"
serde_json = "1.0"
